In [74]:
print("j")

j

In [75]:
import logging 
import pandas as pd

In [76]:
df = pd.read_csv(r'C:\Users\dell\OneDrive\Desktop\DataScience\Projects\Uber_DVC\data\external\ncr_ride_bookings.csv')
df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI

In [77]:
df.shape

(150000, 21)

In [78]:
df = df[df['Booking Status'].isin(['Completed' ,'Incomplete'])]
df.shape

(102000, 21)

In [79]:
df.shape

(102000, 21)

In [80]:
df = df.dropna(subset = 'Booking Status')

In [81]:
df.shape

(102000, 21)

In [82]:
df.isnull().sum()

Date                                      0
Time                                      0
Booking ID                                0
Booking Status                            0
Customer ID                               0
Vehicle Type                              0
Pickup Location                           0
Drop Location                             0
Avg VTAT                                  0
Avg CTAT                                  0
Cancelled Rides by Customer          102000
Reason for cancelling by Customer    102000
Cancelled Rides by Driver            102000
Driver Cancellation Reason           102000
Incomplete Rides                      93000
Incomplete Rides Reason               93000
Booking Value                             0
Ride Distance                             0
Driver Ratings                         9000
Customer Rating                        9000
Payment Method                            0
dtype: int64

In [83]:
cols =  ['Cancelled Rides by Customer' ,'Reason for cancelling by Customer','Cancelled Rides by Driver','Driver Cancellation Reason','Incomplete Rides','Incomplete Rides Reason','Driver Ratings','Customer Rating']

In [84]:
df2 = df[cols]
df2.isnull().sum()

Cancelled Rides by Customer          102000
Reason for cancelling by Customer    102000
Cancelled Rides by Driver            102000
Driver Cancellation Reason           102000
Incomplete Rides                      93000
Incomplete Rides Reason               93000
Driver Ratings                         9000
Customer Rating                        9000
dtype: int64

In [85]:
df['Date']

1         2024-11-29
2         2024-08-23
3         2024-10-21
4         2024-09-16
5         2024-02-06
             ...
149995    2024-11-11
149996    2024-11-24
149997    2024-09-18
149998    2024-10-05
149999    2024-03-10
Name: Date, Length: 102000, dtype: object

In [86]:
df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI
5,2024-02-06,09:44:56,"""CNR4096693""",Completed,"""CID4670564""",Auto,AIIMS,Narsinghpur,5.1,18.1,...,NaN,NaN,NaN,NaN,NaN,316.0,4.85,4.1,4.6,UPI

In [87]:
df3 = df.drop(cols, axis =1 )
df3.shape

(102000, 13)

In [88]:
df3.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Booking Value,Ride Distance,Payment Method
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,237.0,5.73,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,627.0,13.58,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,416.0,34.02,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,737.0,48.21,UPI
5,2024-02-06,09:44:56,"""CNR4096693""",Completed,"""CID4670564""",Auto,AIIMS,Narsinghpur,5.1,18.1,316.0,4.85,UPI

In [89]:
cat = df3.select_dtypes(exclude = 'number').columns
cat

Index(['Date', 'Time', 'Booking ID', 'Booking Status', 'Customer ID',
       'Vehicle Type', 'Pickup Location', 'Drop Location', 'Payment Method'],
      dtype='object')

In [90]:
df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI
5,2024-02-06,09:44:56,"""CNR4096693""",Completed,"""CID4670564""",Auto,AIIMS,Narsinghpur,5.1,18.1,...,NaN,NaN,NaN,NaN,NaN,316.0,4.85,4.1,4.6,UPI

In [91]:
def time_of_day(hour):
    try:
        if 5 <= hour < 12:
            return "Morning"
        elif 12 <= hour < 17:
            return "Afternoon"
        elif 17 <= hour < 21:
            return "Evening"
        else:
            return "Night"

    except Exception as e:
        logging.error(f"Time of day extraction failed due to: {e}")
        raise e 


def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Summer"
    elif month in [6, 7, 8, 9]:
        return "Monsoon"
    else:
        return "Post-Monsoon"
    

def date_time_features(df):
    try:
        logging.info("Starting date and time feature engineering...")

        df['Date'] = pd.to_datetime(df['Date'])
        df['Time'] = pd.to_datetime(df['Time'], format='%H:%M:%S')

        df['Month'] = df['Date'].dt.month
        df['Day'] = df['Date'].dt.day
        df['DayOfWeek'] = df['Date'].dt.day_name()
        df['DayOfWeek_Num'] = df['Date'].dt.dayofweek
        df['Quarter'] = df['Date'].dt.quarter
        df['IsWeekend'] = (df['Date'].dt.dayofweek >= 5).astype(int)
        df['Hour'] = df['Time'].dt.hour
        df['Minute'] = df['Time'].dt.minute
        df['TimeOfDay'] = df['Hour'].apply(time_of_day)
        df['Season'] = df['Month'].apply(get_season)

        df.drop(columns=['Date', 'Time'], inplace=True)

        logging.info("Date and time feature engineering completed.")

        return df

    except Exception as e:
        logging.error(f"Date-Time feature engineering failed due to: {e}")
        raise

In [92]:
df = date_time_features(df)
df.head()

,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,...,Month,Day,DayOfWeek,DayOfWeek_Num,Quarter,IsWeekend,Hour,Minute,TimeOfDay,Season
1,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,NaN,NaN,...,11,29,Friday,4,4,0,18,1,Evening,Post-Monsoon
2,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,NaN,NaN,...,8,23,Friday,4,3,0,8,56,Morning,Monsoon
3,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,NaN,NaN,...,10,21,Monday,0,4,0,17,17,Evening,Post-Monsoon
4,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,NaN,NaN,...,9,16,Monday,0,3,0,22,8,Night,Monsoon
5,"""CNR4096693""",Completed,"""CID4670564""",Auto,AIIMS,Narsinghpur,5.1,18.1,NaN,NaN,...,2,6,Tuesday,1,1,0,9,44,Morning,Winter

In [93]:
df3.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Booking Value,Ride Distance,Payment Method
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,237.0,5.73,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,627.0,13.58,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,416.0,34.02,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,737.0,48.21,UPI
5,2024-02-06,09:44:56,"""CNR4096693""",Completed,"""CID4670564""",Auto,AIIMS,Narsinghpur,5.1,18.1,316.0,4.85,UPI

In [94]:
num_cols =  ['Avg VTAT', 'Avg CTAT', 'Booking Value', 'Ride Distance', 'Month',
       'Day', 'Hour']
cate_cols = ['Vehicle Type', 'Payment Method',
       'Dayofweek', 'time_period']
num_cate_cols = ['Pickup Location','Drop Location']

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 102000 entries, 1 to 149999
Data columns (total 29 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Booking ID                         102000 non-null  object
 1   Booking Status                     102000 non-null  object
 2   Customer ID                        102000 non-null  object
 3   Vehicle Type                       102000 non-null  object
 4   Pickup Location                    102000 non-null  object
 5   Drop Location                      102000 non-null  object
 6   Avg VTAT                           102000 non-null  float64
 7   Avg CTAT                           102000 non-null  float64
 8   Cancelled Rides by Customer        0 non-null       float64
 9   Reason for cancelling by Customer  0 non-null       object
 10  Cancelled Rides by Driver          0 non-null       float64
 11  Driver Cancellation Reason         0 non-null       object
 12  Incomplete Rides                   9000 non-null    float64
 13  Incomplete Rides Reason            9000 non-null    object
 14  Booking Value                      102000 non-null  float64
 15  Ride Distance                      102000 non-null  float64
 16  Driver Ratings                     93000 non-null   float64
 17  Customer Rating                    93000 non-null   float64
 18  Payment Method                     102000 non-null  object
 19  Month                              102000 non-null  int32
 20  Day                                102000 non-null  int32
 21  DayOfWeek                          102000 non-null  object
 22  DayOfWeek_Num                      102000 non-null  int32
 23  Quarter                            102000 non-null  int32
 24  IsWeekend                          102000 non-null  int64
 25  Hour                               102000 non-null  int32
 26  Minute                             102000 non-null  int32
 27  TimeOfDay                          102000 non-null  object
 28  Season                             102000 non-null  object
dtypes: float64(9), int32(6), int64(1), object(13)
memory usage: 21.0+ MB

In [96]:
df.columns

Index(['Booking ID', 'Booking Status', 'Customer ID', 'Vehicle Type',
       'Pickup Location', 'Drop Location', 'Avg VTAT', 'Avg CTAT',
       'Cancelled Rides by Customer', 'Reason for cancelling by Customer',
       'Cancelled Rides by Driver', 'Driver Cancellation Reason',
       'Incomplete Rides', 'Incomplete Rides Reason', 'Booking Value',
       'Ride Distance', 'Driver Ratings', 'Customer Rating', 'Payment Method',
       'Month', 'Day', 'DayOfWeek', 'DayOfWeek_Num', 'Quarter', 'IsWeekend',
       'Hour', 'Minute', 'TimeOfDay', 'Season'],
      dtype='object')

In [97]:
df = pd.read_csv(r'C:\Users\dell\OneDrive\Desktop\DataScience\Projects\Uber_DVC\data\processed\X_train.csv')
df.head()

,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Booking Value,Ride Distance,Payment Method,Month,Day,DayOfWeek,Quarter,IsWeekend,Hour,TimeOfDay,Season
0,2.0,43.0,108.0,0.485580,1.416916,0.735123,1.251330,1.0,1.503952,-0.568913,5.0,3.0,0.0,0.930042,1.0,3.0
1,2.0,30.0,163.0,1.177274,-0.590352,-0.176238,-1.111307,0.0,1.503952,-1.229799,4.0,3.0,0.0,0.727352,1.0,3.0
2,1.0,8.0,39.0,-1.623067,-0.963655,-1.555437,-1.067258,3.0,-1.720074,-1.703322,5.0,0.0,0.0,-0.790517,2.0,3.0
3,0.0,150.0,81.0,0.874257,-0.951374,1.172558,1.003157,0.0,0.746521,1.134106,4.0,2.0,0.0,-0.430385,0.0,0.0
4,0.0,26.0,155.0,0.334715,0.928887,-0.411777,0.030512,3.0,-0.673884,1.508783,5.0,1.0,0.0,0.930042,1.0,2.0

In [98]:
df.columns

Index(['Vehicle Type', 'Pickup Location', 'Drop Location', 'Avg VTAT',
       'Avg CTAT', 'Booking Value', 'Ride Distance', 'Payment Method', 'Month',
       'Day', 'DayOfWeek', 'Quarter', 'IsWeekend', 'Hour', 'TimeOfDay',
       'Season'],
      dtype='object')